version: '3'

services:
    frontend:
        build:
            context: ../../
            dockerfile: .devcontainer/frontend/Dockerfile
        environment:
            PYTHONPATH: /usr/src/app
            TZ: Asia/Tokyo
        # env_file:
        #     - ./envfile
        #     - ../.env
        volumes:
            - scripts:/usr/src/app/
            - node_modules:/usr/src/app/frontend/node_modules
            - mnt:/usr/src/mnt
        ports:
            - 5173:5173
        # command: /bin/sh -c "npm install; npm run dev"
        command: /bin/sh -c "sudo npm run dev"
        privileged: true
        tty: true

volumes:
    scripts:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "../../"
    mnt:
    node_modules: